[package]
name = "jadata"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
encoding_rs = "0.8.34"
eyre = "0.6.12"
serde = "1.0.204"
serde-xml-rs = "0.8.1"
xml-rs = "0.8.27"
